"""Initial schema: users, ports, vessels

Revision ID: ef1b9070a7da
Revises: 
Create Date: 2026-07-30 12:15:10.184622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1b9070a7da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('berth_capacity', sa.Integer(), nullable=True),
    sa.Column('active_berths_used', sa.Integer(), nullable=True),
    sa.Column('congestion_level', sa.String(), nullable=True),
    sa.Column('congestion_percent', sa.Integer(), nullable=True),
    sa.Column('waiting_vessels', sa.Integer(), nullable=True),
    sa.Column('avg_wait_hours', sa.Float(), nullable=True),
    sa.Column('status_label', sa.String(), nullable=True),
    sa.Column('primary_exports', sa.JSON(), nullable=True),
    sa.Column('max_vessel_draught_meters', sa.Float(), nullable=True),
    sa.Column('total_annual_teu', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_code'), 'ports', ['code'], unique=True)
    op.create_index(op.f('ix_ports_name'), 'ports', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vessels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mmsi', sa.Integer(), nullable=False),
    sa.Column('imo', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('vessel_type', sa.String(), nullable=True),
    sa.Column('ship_type_code', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('destination_port', sa.String(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('width_meters', sa.Float(), nullable=True),
    sa.Column('draught_meters', sa.Float(), nullable=True),
    sa.Column('capacity_teu', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_risk_reason', sa.String(), nullable=True),
    sa.Column('speed_history', sa.JSON(), nullable=True),
    sa.Column('cargo_summary', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_imo'), 'vessels', ['imo'], unique=False)
    op.create_index(op.f('ix_vessels_mmsi'), 'vessels', ['mmsi'], unique=True)
    op.create_table('berth_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('berth_number', sa.String(), nullable=False),
    sa.Column('berth_name', sa.String(), nullable=True),
    sa.Column('max_vessel_length_meters', sa.Float(), nullable=True),
    sa.Column('max_draught_meters', sa.Float(), nullable=True),
    sa.Column('berth_type', sa.String(), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('current_vessel_mmsi', sa.Integer(), nullable=True),
    sa.Column('current_vessel_name', sa.String(), nullable=True),
    sa.Column('occupied_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_operation', sa.String(), nullable=True),
    sa.Column('crane_count', sa.Integer(), nullable=True),
    sa.Column('loading_progress_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_congestion_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('congestion_percent', sa.Integer(), nullable=False),
    sa.Column('waiting_vessels', sa.Integer(), nullable=True),
    sa.Column('avg_wait_hours', sa.Float(), nullable=True),
    sa.Column('disruption_flag', sa.Boolean(), nullable=True),
    sa.Column('disruption_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_disruptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('disruption_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('flagged_by_user_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_managers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('security_pass_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_port_managers_employee_id'), 'port_managers', ['employee_id'], unique=True)
    op.create_table('vessel_arrivals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=False),
    sa.Column('vessel_mmsi', sa.Integer(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('vessel_type', sa.String(), nullable=True),
    sa.Column('vessel_flag', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ata', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_berth_id', sa.String(), nullable=True),
    sa.Column('berth_assignment_status', sa.String(), nullable=True),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('cargo_tonnage', sa.Float(), nullable=True),
    sa.Column('teu_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_berth_id'], ['berth_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessel_arrivals')
    op.drop_index(op.f('ix_port_managers_employee_id'), table_name='port_managers')
    op.drop_table('port_managers')
    op.drop_table('port_disruptions')
    op.drop_table('port_congestion_history')
    op.drop_table('berth_slots')
    op.drop_index(op.f('ix_vessels_mmsi'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ports_name'), table_name='ports')
    op.drop_index(op.f('ix_ports_code'), table_name='ports')
    op.drop_table('ports')
    # ### end Alembic commands ###
